
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aleja
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    administracion admin = new administracion();
    Scanner r = new Scanner(System.in);
    private DefaultTableModel modelo;
    public ArrayList<Object> lista = new ArrayList<Object>();
    public ArrayList<Integer> t = new ArrayList<Integer>();

    public interfaz() {
        initComponents();
        //
        setLocationRelativeTo(null);//pone la pantalla en el centro
        //
        modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(172);
        Color ivory = new Color(255, 255, 255);
        jTable1.setOpaque(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setBackground(ivory);
        jTable1.getTableHeader().setBackground(ivory);
        iniciar();
    }

    public void iniciar() {
        int espacio;
        //numero aleatorios entre 10 y 3

        for (int i = 0; i < 10; i++) {
            espacio = (int) (Math.random() * (10 - 3 + 1) + 3);
            PrimerAjuste nuevo = new PrimerAjuste("h", admin.buscarindice(), espacio);
            admin.addContenidoInicial(nuevo);
        }
        LinkedList<PrimerAjuste> cont = admin.mandarLista();
        for (int i = 0; i < cont.size(); i++) {
            //String lista = cont.get(i).getTipo() + " " + cont.get(i).getEmpieza() + " l:" + cont.get(i).getLongitud();
            lista = admin.mandarInfo();
            modelo.addRow((Object[]) lista.get(i));
            int aux = cont.get(i).getLongitud() - 4;
            if (cont.get(i).getLongitud() < 5) {
                jTable1.setRowHeight(i, (30 + aux));
            } else {
                aux = cont.get(i).getLongitud() - 10;
                jTable1.setRowHeight(i, (50 + aux));
            }
        }
    }

    public void actualizarTabla() {
        //primero eliminar todas los procesos
        int tt = modelo.getRowCount();
        for (int i = tt - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        //luego actualizar la memoria con los nuevos
        lista.clear();
        lista = admin.mandarInfo();
        LinkedList<PrimerAjuste> cont = admin.mandarLista();
        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow((Object[]) lista.get(i));
            int aux = cont.get(i).getLongitud() - 4;
            if (cont.get(i).getLongitud() < 5) {
                jTable1.setRowHeight(i, (30 + aux));
            } else {
                aux = cont.get(i).getLongitud() - 10;
                jTable1.setRowHeight(i, (50 + aux));
            }

            //System.out.println("Tamañoo  :"+ t.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsertar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 700));
        setMinimumSize(new java.awt.Dimension(550, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(85, 85, 85));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(205, 201, 195));
        jTable1.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 510));

        btnInsertar.setBackground(new java.awt.Color(120, 147, 149));
        btnInsertar.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("    INSERTAR");
        btnInsertar.setToolTipText("");
        btnInsertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertar.setOpaque(true);
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 160, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(550, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtP.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtP.setForeground(new java.awt.Color(204, 204, 204));
        txtP.setText("Ingrese longitud del proceso...");
        txtP.setBorder(null);
        txtP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtPMouseReleased(evt);
            }
        });
        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });
        jPanel1.add(txtP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 280, 20));

        jLabel2.setText("__________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 290, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("LONGITUD DE PROCESO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(229, 227, 201));

        salir.setBackground(new java.awt.Color(180, 207, 176));
        salir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        salir.setForeground(new java.awt.Color(102, 102, 102));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setOpaque(true);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(512, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 40));

        jLabel3.setBackground(new java.awt.Color(180, 207, 176));
        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 560, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        // TODO add your handling code here:
        int numero = Integer.valueOf(txtP.getText());
        PrimerAjuste nuevo = new PrimerAjuste("p", admin.buscarindice(), numero);
        // agrar el espacio de memerio 
        if (admin.addContenido(nuevo)== true) {
            jLabel3.setText("  Proceso ingresado");
            
        }else {
            JOptionPane.showMessageDialog(null, "No hay suficiente espacio");
        }
       
        actualizarTabla();
        admin.mostrar();
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void txtPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPMousePressed
        // TODO add your handling code here:
        if (txtP.getText().equals("Ingrese longitud del proceso...")) {
            txtP.setText("");
            txtP.setForeground(Color.black);
        }


    }//GEN-LAST:event_txtPMousePressed

    private void txtPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPMouseReleased
      

    }//GEN-LAST:event_txtPMouseReleased

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
        salir.setBackground(Color.red);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        // TODO add your handling code here:
        salir.setBackground(new Color(180, 207, 176));
    }//GEN-LAST:event_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel salir;
    private javax.swing.JTextField txtP;
    // End of variables declaration//GEN-END:variables
}
